import os,json,urllib.request,urllib.parse
KEY=os.environ.get("SPORTSGAMEODDS_API_KEY")
if not KEY: raise SystemExit("Missing SPORTSGAMEODDS_API_KEY")
q=urllib.parse.urlencode({"leagueID":"NHL","oddsAvailable":"true","includeOpposingOdds":"true","includeOpenCloseOdds":"true","limit":"50"})
r=urllib.request.Request("https://api.sportsgameodds.com/v2/events?"+q,headers={"x-api-key":KEY,"User-Agent":"brnsy-props/1.0"})
with urllib.request.urlopen(r,timeout=30) as x: d=json.load(x)
if not d.get("success",True): raise SystemExit(str(d.get("error")))
os.makedirs("data/raw",exist_ok=True)
json.dump(d,open("data/raw/events.json","w"))
print("Fetched",len(d.get("data",[])),"events")
